name: DT-Chat CI

on:
  push:
    branches: ["develop","main","feature/*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: | 
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: swatinem/rust-cache@v2

      - run: cargo fmt --all -- --check
        continue-on-error: true
      - run: cargo clippy
      - run: cargo test --bins --tests